travis:
  secure:
    BINSTAR_TOKEN: gnqkhQln4To4NoCy5fAuwC/lxRB51NW/3hq4KE7X0TDgG4i2Ru7AAAQ7vqH59hgi6ZJIxUYMOirgnsnROBD9/11oZVc3bDILZsF64qRfZY40zrJVVx3lsf7VdwCdswQPhVIOCvB/y6LL97fJwa0Q9sQy8bozKkVwv7S+yq5o+WfAb+14+ymsdaM4fPWuFqFX9zkuxwmkg+TfCqzDATlBPtkQwlrn39CQUjiOnITJvFA+ED24NNXadtyuU5du1Y2RBQpelCk36AVjigESGmu6uZp1JEc1cj1yX1TmEmkDwe2HD/BYB9EFurL4diKcO1iqO4QHjVG1/lFolrw67zA0oIgQ1Tym8Zeevth4L4zpCDbibN+hKwHFdeEoYe53jP5s/GYUhVONUE0BA+R1dmLld3/cHoRUVN2zDhSllqefS1K2UGLBSm5EuM286gvolMb1UCNPDseg/+bwmq/nUOpcQOBxvsqiIhqIlJwFg1DsDA9Z4fhzWu9QtdoK8Ijc68bGORZrR0FwqEzdittlfqYUQBuzJY67jISALd0fUV481OaHpLeLmjcP0dcE5SKO64N0wXTCVfYX2sVL5H4i7Wtti+I92sJCD83CDbQtfPB8A0MXmabM4cQIBknTeRPplMvU8Dx0CjXkGlcIeaQbiNHSUVEVCgr/e++gsJV4PwzHXlo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
