noarch_platforms:
  - linux_64
  - osx_64
  - osx_arm64
  - win_64
  - linux_ppc64le
  - linux_aarch64
build_platform:
  osx_arm64: osx_64
provider:
  linux_ppc64le: default
  linux_aarch64: default
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
conda_build:
  pkg_format: '2'
